services:
  - type: web
    name: bybit-scanner-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      # CRITICAL: Set these in Render Dashboard Environment Variables
      # DO NOT put real values here for security reasons
      - key: BOT_TOKEN
        sync: false  # REQUIRED: Set in Render dashboard
      - key: ADMIN_ID  
        sync: false  # REQUIRED: Set in Render dashboard
      - key: CHANNEL_ID
        sync: false  # REQUIRED: Set in Render dashboard
      - key: SUBSCRIBER_ID
        value: "0"  # Optional: Default subscriber ID
      - key: USE_PUBLIC_APIS_ONLY
        value: true
      - key: SCANNER_INTERVAL
        value: 60
      - key: PUMP_THRESHOLD
        value: 5.0
      - key: DUMP_THRESHOLD
        value: -5.0
      - key: BREAKOUT_THRESHOLD
        value: 3.0
      - key: VOLUME_THRESHOLD
        value: 50.0
      - key: SIGNAL_STRENGTH_THRESHOLD
        value: 70.0
      - key: WHALE_THRESHOLD
        value: 15000.0
      - key: LIQUIDITY_RATIO_THRESHOLD
        value: 3.0
      - key: RSI_OVERBOUGHT
        value: 75.0
      - key: RSI_OVERSOLD
        value: 25.0
      - key: SPREAD_THRESHOLD
        value: 0.3
      - key: RANGE_BREAK_THRESHOLD
        value: 1.2
      - key: DATABASE_PATH
        value: ./bot_data.db
      - key: PORT
        value: 8080
      - key: RENDER_SERVICE_NAME
        value: public-api-crypto-scanner