services:
  - type: web
    name: bybit-scanner-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    # Environment variables should be set in Render dashboard
    # for security reasons - not hardcoded here