services:
  - type: web
    name: bybit-scanner-bot
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7465275468:AAE8JWqC-tBADGrd6qXrwdrOc7bampsm_Iw
      - key: ADMIN_ID
        value: 7974254350
      - key: BYBIT_API_KEY
        value: 1Lf8RrbAZwhGz42UNY
      - key: BYBIT_SECRET
        value: your_bybit_secret_here
      - key: SCANNER_INTERVAL
        value: 60
      - key: PUMP_THRESHOLD
        value: 5.0
      - key: DUMP_THRESHOLD
        value: -5.0
      - key: BREAKOUT_THRESHOLD
        value: 3.0
      - key: DATABASE_PATH
        value: ./bot_data.db